### ISSUE TITLE
web3.eth.Contract is not a constructor

### ISSUE THREAD

**Issue by Aeroxander** [0xcert/erc721-validator#16]
I'm getting

> web3.eth.Contract is not a constructor

 at line 40 of validator.ts

I've read that you don't need "new" in front the constructor, but this is only with web3 versions <1

I tried to fork the package but then I get this error during my build 😅 :

> This dependency was not found:
> * @0xcert/erc721-validator in ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./pages/settings.vue?vue&type=script&lang=js&

Any help is greatly appreciated!

**Comment by MoMannn** [comment]
Did you do `npm install` first? I just tried and it builds normally. What environment are you using? On mac os I'm not having any problems and the same code is running live on linux as well. 

Also check out: https://github.com/0xcert/erc721-validator-api for an example on how to use it. 

There is also an article in the doing on how everything works.

**Comment by MoMannn** [comment]
@Aeroxander [Here](https://0xcert.org/news/live-testing-smart-contracts-with-estimategas-william-entriken-tadej-vengust/) is an article on how everything works.
