### ISSUE TITLE
the check for balanceOf(0) does not seem to detect revert

### ISSUE THREAD

**Issue by wighawag** [0xcert/erc721-validator#17]
I have an ERC721 contract on the mainnet at : 0x266003AfA9976D72565cac0bd840C276b01aE34f

and when I test it against the validator at https://erc721validator.org/?address=0x266003AfA9976D72565cac0bd840C276b01aE34f
It shows that balanceOf(address(0)) does not throw/

But when I execute the eth_call myself to an infura node with
```
{
	"jsonrpc": "2.0",
	"id": 1,
	"method": "eth_call",
	"params": [{
		"to": "0x266003AfA9976D72565cac0bd840C276b01aE34f",
		"data": "0x70a082310000000000000000000000000000000000000000000000000000000000000000"
	}, "latest"]
}
```

It gives me 
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": "0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000156f776e6572206973207a65726f20616464726573730000000000000000000000"
}
```

which is a revert-reason string so the call indeed revert

In comparison the 0xcert implementation when called with the same request, 

```
{
	"jsonrpc": "2.0",
	"id": 1,
	"method": "eth_call",
	"params": [{
		"to": "0xf176d7bcdD07f8e474877095870685Ef0CCcCb2D",
		"data": "0x70a082310000000000000000000000000000000000000000000000000000000000000000"
	}, "latest"]
}
```

I get
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": "0x"
}
```
which is also the response (albeit different) corresponding to a revert/throw

Maybe it is the web3 `estimateGas` call that does not error out here : 
https://github.com/0xcert/erc721-validator/blob/master/src/validator.ts#L47

because it does not consider the error-reason string as an error
See also https://github.com/ethereum/go-ethereum/issues/19027

**Comment by wighawag** [comment]
@fulldecent ^

**Comment by MoMannn** [comment]
@wighawag This indeed seems the reason. We need to change the way we handle reverted calls.

**Comment by MoMannn** [comment]
#18
