### ISSUE TITLE
Review popular contracts

### ISSUE THREAD

**Issue by fulldecent** [0xcert/erc721-validator#7]
Here are some projects, please find ALL deployed 721 or notable 721 contracts and validate them. Paste in here the list of all issues that are found.

Due date Tue July 24th.

# Follow on work

- [x] Send to 0xcert #marketing

**Comment by fulldecent** [comment]
Due date: Tuesday June 24

**Comment by MoMannn** [comment]
https://docs.google.com/spreadsheets/d/1e1hELMVelEY0h9q9K2Si3UtH2frw9yteYrjEJLTNaks/edit#gid=0
